// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msgproto is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	SendMsg
	ReplyMsg
*/
package msgproto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SendMsg struct {
	MsgFrom          *string `protobuf:"bytes,1,req" json:"MsgFrom,omitempty"`
	MsgSendTo        *string `protobuf:"bytes,2,req" json:"MsgSendTo,omitempty"`
	MsgType          *string `protobuf:"bytes,3,req" json:"MsgType,omitempty"`
	MsgContent       *string `protobuf:"bytes,4,req" json:"MsgContent,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendMsg) Reset()         { *m = SendMsg{} }
func (m *SendMsg) String() string { return proto.CompactTextString(m) }
func (*SendMsg) ProtoMessage()    {}

func (m *SendMsg) GetMsgFrom() string {
	if m != nil && m.MsgFrom != nil {
		return *m.MsgFrom
	}
	return ""
}

func (m *SendMsg) GetMsgSendTo() string {
	if m != nil && m.MsgSendTo != nil {
		return *m.MsgSendTo
	}
	return ""
}

func (m *SendMsg) GetMsgType() string {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return ""
}

func (m *SendMsg) GetMsgContent() string {
	if m != nil && m.MsgContent != nil {
		return *m.MsgContent
	}
	return ""
}

type ReplyMsg struct {
	Isok             *bool  `protobuf:"varint,1,req" json:"Isok,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReplyMsg) Reset()         { *m = ReplyMsg{} }
func (m *ReplyMsg) String() string { return proto.CompactTextString(m) }
func (*ReplyMsg) ProtoMessage()    {}

func (m *ReplyMsg) GetIsok() bool {
	if m != nil && m.Isok != nil {
		return *m.Isok
	}
	return false
}

func init() {
}
